# Maintainer: Andrey Platonov <poluandrey@gmail.com>
pkgname=chattix
_chat=${CHAT:-mattermost}
_branch=${BRANCH:-wip}
pkgver=${PKGVER:-autogenerated}
pkgrel=${PKGREL:-1}
pkgdesc="tools for integrate zabbix events into chats"
arch=('i686' 'x86_64')
license=('GPL')
depends=(
)
makedepends=(
        'go'
        'git'
)
backup=(
    "etc/chattix/zabbix-to-$_chat.conf"
    "etc/chattix/chattixd.conf"
)

source=(
        "git+https://github.com/zarplata/chattix.git#branch=$_branch"
)

md5sums=(
        'SKIP'
)


build() {
    cd "$srcdir/$pkgname"
    make
}

package() {
    cd "$srcdir/$pkgname"

    find .out/ -type f -executable | while read filename; do
            install -DT "$filename" "$pkgdir/usr/bin/$(basename $filename)"
    done

    install -DT -m0644 "action_ack/config.conf" "$pkgdir/etc/chattix/chattixd.conf"
    install -DT -m0644 "webhook/config.conf" "$pkgdir/etc/chattix/zabbix-to-$_chat.conf"
    install -DT -m0644 "systemd/chattixd.service" "$pkgdir/lib/systemd/system/chattixd.service"
}

